session_name: ${MUDMUX_TMUX_SESSION_NAME}

environment:
  MUDMUX_DOCKER_SERVICE: ${MUDMUX_DOCKER_SERVICE}
  MUDMUX_DOCKER_IMAGE: ${MUDMUX_DOCKER_IMAGE}
  MUDMUX_COMMS_LOG: ${MUDMUX_COMMS_LOG}
  MUDMUX_PROFILE_ESC: ${MUDMUX_PROFILE_ESC}
  MUDMUX_EDITOR: ${MUDMUX_EDITOR}
  MUDMUX_NOTES_FILE: ${MUDMUX_NOTES_FILE}

windows:

  - window_name: base
    layout: main-vertical

    options:
      main-pane-width: 75

    panes:

      - shell_command:
        - docker-compose run ${MUDMUX_DOCKER_SERVICE}
        focus: true

      - shell_command:
        - clear
        - tail -n50 -f ${MUDMUX_COMMS_LOG}
        - tmux select-layout main-horizontal

      - shell_command:

        # This delay is important for opening emacs, which fails without. It also
        # allows the window time to open, which makes profile switching work.
        - sleep 1

        - echo -e ${MUDMUX_PROFILE_ESC}
        - ${MUDMUX_EDITOR} ${MUDMUX_NOTES_FILE}